name: CI
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      publish_release:
        description: 'Create a release'
        type: boolean
        required: false
        default: false
  push:
    branches:
    - dev
    - 'releases/**'
    - dev-usertype-null-as-member # temporary branch for testing
    tags:
      - "v*"
  pull_request:
    branches: [ "dev", "master", "releases/**" ]

jobs:
  call-ci-workflow:
    uses: rcorbacho/EntraCP/.github/workflows/reusable-ci.yml@dev-usertype-null-as-member
    with:
      project_name: ${{ vars.PROJECT_NAME }}
      publish_release: ${{ inputs.publish_release || false }}
    secrets:
      base64_encoded_signingkey: ${{ secrets.BASE64_ENCODED_SIGNINGKEY }}
